#!/bin/sh -e

for patch in *.diff
do
    /opt/gnu/patch/bin/patch -p1 < "$patch"
done

mv mine.config.def.h config.def.h

mkdir -p "$1/etc/kiss/defconfig/st"
install -Dm 755 config.def.h "$1/etc/kiss/defconfig/st"

make PREFIX=/usr DESTDIR="$1" install
