#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --libexecdir=/usr/lib \
    --localstatedir=/var \
    --with-modules \
    --without-all \
    --without-x \
    --with-x-toolkit=no \
    --with-x=no \
    --with-xml2=yes

mkdir -p "$1/usr/share/emacs/site-lisp"
cat << EOF > "$1/usr/share/emacs/site-lisp/site-start.el"
;; garbage collect less often for better performance
(setq gc-cons-threshold 100000000)

;; fix ugly
(menu-bar-mode -1)

;; some minimal better defaults
(setq-default indent-tabs-mode nil
              tab-width 8
              fill-column 80)
(prefer-coding-system 'utf-8)
(set-default-coding-systems 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)

;; no littering
(setq backup-directory-alist \`(("." . ,(concat user-emacs-directory
                                                 "backups"))))
;; a kiss front-end
(defun kiss ()
  "A minimalist front-end to the KISS Linux package manager"
  (interactive)
  (with-temp-buffer
    (if (not (string-match "root@" (pwd)))
        (cd (concat "/su:root@"system-name":"default-directory)))
    (setq-local
     my-read
     (read-string "kiss [b|c|i|l|r|s|u] [pkg] [pkg] [pkg] " ""))
    (async-shell-command (concat "kiss " my-read "|| echo err $?"))
    (delete-other-windows)
    (switch-to-buffer "*Async Shell Command*")))

;; optionally allow user to bootstrap straight.el
(defun straight-bootstrap ()
  (interactive)
  (if (bound-and-true-p use-straight-package)
    (progn
      (defvar bootstrap-version)
    (let ((bootstrap-file
           (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
          (bootstrap-version 5))
      (unless (file-exists-p bootstrap-file)
        (with-current-buffer
            (url-retrieve-synchronously
             "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
             'silent 'inhibit-cookies)
          (goto-char (point-max))
          (eval-print-last-sexp)))
      (load bootstrap-file nil 'nomessage)))
    (message "To use this feature use-straight-package cannot be nil")))
EOF

make DESTDIR="$1" install
