#!/bin/sh -e

wget https://dl.suckless.org/tools/dmenu-4.9.tar.gz

tar xzvf dmenu-4.9.tar.gz

sh

cd dmenu-4.9

cp ../savedconfig/mine.config.def.h config.h

make X11INC=/usr/include/X11 X11LIB=/usr/lib/X11 FREETYPEINC=/usr/include/freetype2
make PREFIX=/$HOME/.local install

cd -

rm -rf dmenu*
