#!/bin/bash

while ! xprop -root | grep -q Free; do sleep 1; done
internal="LVDS1"
external="VGA1"
if xrandr | grep -q "$external connected" ; then  xrandr --output "$internal" --off --output "$external" --auto ; fi
redshift -x && redshift -O 2000
xset +dpms
xset s 1800
xset b off
xset dpms 0 0 1860

xset r rate 200 60
setxkbmap -option ctrl:swap_lalt_lctl -option caps:menu

touchpad="$(xinput list | awk '/TouchPad/ { print $7 }')"
xinput set-prop ${touchpad#id=} 'libinput Tapping Enabled' 1
xinput set-prop ${touchpad#id=} 'libinput Accel Speed' 0.4

xsetroot -solid black -cursor_name left_ptr
xrdb -merge ~/.Xresources

dunst &
picom --backend glx &

exec dbus-launch --exit-with-session emacs
